version: "3.8"
services:
  spring-boot-app:
    image: expense-tracker-backend
    build:
      context: "./"
      dockerfile: "Dockerfile"
#    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/expense_tracker?useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Razan123"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
  mysqldb:
    image: "mysql:8"
#    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: expense_tracker
      MYSQL_ROOT_PASSWORD: Razan123